main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[build]
command = "cargo install -q worker-build --version 0.0.8 && worker-build --release"

[env.production]
name = "xfuraffinity"
vars = { WORKERS_RS_VERSION = "0.0.11" }

[env.staging]
name = "xfuraffinity-staging"
vars = { WORKERS_RS_VERSION = "0.0.11" }
